# **Intializing a Tensor**

A pytorch tensor is basically the same as a numpy array. It doesnot know anything about deeplearning or computational graphs or gradient....


*   Tensors are useful in multiple ways. Apart from using them as base data structures for images, one more prominent use for them is when tensors are leveraged to initialize the weights connecting different layers of a neural network.


*   In this section, we will practice the different ways of initializing a tensor object:



# **Import pytorch and initialize a tensor by calling torch.tensor in alist**

In [1]:
import torch

x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

# Next access the Tensor object shape and dtype

In [2]:
# one entity of two items
print(x.shape)


# two entity of one item
print(y.shape)

# data type
print(x.dtype)


torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


The data type of all elements within a tensor is the same. That means if a tensor contains data of different data types (such as a Boolean, an integer, and a float)

In [3]:
x = torch.tensor([False,1,2.0])
print(x)

tensor([0., 1., 2.])


As you can see in the output of the preceding code, False, which was a Boolean, and 1, which was an integer, were converted into floating-point numbers.

# **Generate a tensor object that has three rows and four columns filled with zeros:**

In [4]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# **Generate a tensor object that has three rows and four columns filled with ones:**

In [5]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Generate three rows and four columns of values between o and 10(including the loss value but not including the high 

In [6]:
torch.randint(low=0,high=10,size=(3,4))

tensor([[3, 2, 0, 9],
        [4, 7, 1, 8],
        [9, 3, 6, 7]])

# **Generate random numbers between 0 and 1 with three rows and four columns:**

In [9]:
torch.rand((3,4))

tensor([[0.9204, 0.9696, 0.7566, 0.2833],
        [0.7567, 0.6157, 0.2556, 0.7201],
        [0.1181, 0.0978, 0.9373, 0.3773]])

Generate numbers that follow a normal distribution with three rows and four columns:

In [11]:
torch.randn((3,4))

tensor([[ 0.0360, -0.2727,  0.5882,  0.8378],
        [-0.5962, -0.1194,  0.3599, -0.3443],
        [-0.7968, -0.1031, -0.8240,  0.5131]])

Finally we can directly convert a Numpy array in to torch tensor using torch.tensor..

In [13]:
import numpy as np

In [14]:
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


# Now that we have learned about intializing tensor objects, we will learn about various matrix operations