# **Operations on Tensor**


Similar to Numpy,you can perform various basics operations on tensor objects.Parallel to neural network work operations are the matrix multiplication of input with weights the addition of bias terms and reshaping input or weight values when required..


# Multiplication of all elements present in x by 10 can be performed using the following code..

In [1]:
import torch
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(x*10)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


## Adding 10 to the elements in x and storing the resulting tensor in y can be performed using the following code

In [2]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
y = x.add(10)
print(y)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])


# Reshaping a tensor can be performed using the following code

In [3]:
y = torch.tensor([2,3,1,0])
y = y.view(4,1)
print(y)

tensor([[2],
        [3],
        [1],
        [0]])




Another way to reshape a tensor is by using the squeeze method, 
  torch.squeeze() returns a tensor with all the dimensions of input of size "1" removed.. **



In [6]:
x = torch.randn(10,1,10)
z1 = torch.squeeze(x,1) # similar to np.squeeze(x,1)
# The same operations can be directly performed..
# x by calling squeeze and the dimension to squeeze out

z2 = x.squeeze(1)
# All the elements in both tensor are equal..
print('Squeeze:\n', x.shape,z1.shape)


Squeeze:
 torch.Size([10, 1, 10]) torch.Size([10, 10])


# ***Another way to using  torch.squeeze ***

In [7]:
x = torch.randn(1,2,1,2,1,1,2)
y= torch.squeeze(x)
print('Squeeze:\n', x.shape,y.shape)

Squeeze:
 torch.Size([1, 2, 1, 2, 1, 1, 2]) torch.Size([2, 2, 2])


# The opposite of squeeze is unsqueeze, which means we add a dimension to the matrix, which can be performed using the following code

In [8]:
x = torch.randn(10,10)
print(x.shape)
#torch.size(10,10)
z1 = x.unsqueeze(0)
print(z1.shape)
#torch.size(1,10,10)
# the same can be acheived using [None] indexing
## Adding None will auto create a fake dim at the
# specified axis

x = torch.randn(10,10)
z2,z3,z4 = x[None],x[:,None],x[:,:,None]
print(z2.shape,z3.shape,z4.shape)

torch.Size([10, 10])
torch.Size([1, 10, 10])
torch.Size([1, 10, 10]) torch.Size([10, 1, 10]) torch.Size([10, 10, 1])


Using None for indexing is a fancy way of unsqueezing, as shown, and will be used often in this book for creating fake channel/batch dimensions.

# Matrix Multiplication of two different tensors can be performed using the following code..

In [9]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([5,6,7,8])
print(torch.matmul(x, y))

tensor(70)


In [10]:
print(x@y)

tensor(70)


# Similar to concatenate in Numpy ,we can perform concatenation of tensors using cat method...

In [11]:
import torch
x= torch.randn(10,10,10)
z = torch.cat([x,x],axis=0) # similar to np.concatenate()
print("cat axis 0",x.shape,z.shape)


cat axis 0 torch.Size([10, 10, 10]) torch.Size([20, 10, 10])


On index One...

In [12]:
z =torch.cat([x,x],axis=1)
print("cat axis",x.shape,z.shape )

cat axis torch.Size([10, 10, 10]) torch.Size([10, 20, 10])


# **Extraction of the maximum value in a tensor can be performed using the following code:**

In [13]:
x = torch.arange(25).reshape(5,5)
print("max :",x.shape,x.max())

max : torch.Size([5, 5]) tensor(24)


# We can extract the maximum value along with row index where the maximum value will be present...

In [14]:
x.max(0)

torch.return_types.max(values=tensor([20, 21, 22, 23, 24]), indices=tensor([4, 4, 4, 4, 4]))

Note that, in the preceding output, we are fetching the maximum values across dimension 0, which is the rows of the tensor. Hence, the maximum values across all rows are the values present in the 4th index and hence the indices output is all fours too. Furthermore, .max returns both the maximum values and the location (argmax) of the maximum values.

# Similarly the output when fetching the maximum value across columns is as follows..

In [15]:
m=x.max(1)
print("max in axis 1: \n",m)

max in axis 1: 
 torch.return_types.max(
values=tensor([ 4,  9, 14, 19, 24]),
indices=tensor([4, 4, 4, 4, 4]))


In [16]:
m,arg = x.max(1)
print('max in axis 1 :\n',m,arg)

max in axis 1 :
 tensor([ 4,  9, 14, 19, 24]) tensor([4, 4, 4, 4, 4])


In [17]:
x = torch.randn(10,20,30)
z = x.permute(2,0,1)
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([10, 20, 30]) torch.Size([30, 10, 20])


Note that the shape of the tensor changes when we perform permute on top of the original tensor.


*   Never reshape (that is, use tensor.view on) a tensor to swap the dimensions. Even though Torch will not throw an error, this is wrong and will create unforeseen results during training. If you need to swap dimensions, always use permute.



In [21]:
dir(torch.Tensor)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__cuda_array_interface__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__

In [20]:
help(torch.Tensor.view)

Help on method_descriptor:

view(...)
    view(*shape) -> Tensor
    
    Returns a new tensor with the same data as the :attr:`self` tensor but of a
    different :attr:`shape`.
    
    The returned tensor shares the same data and must have the same number
    of elements, but may have a different size. For a tensor to be viewed, the new
    view size must be compatible with its original size and stride, i.e., each new
    view dimension must either be a subspace of an original dimension, or only span
    across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
    contiguity-like condition that :math:`\forall i = d, \dots, d+k-1`,
    
    .. math::
    
      \text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]
    
    Otherwise, it will not be possible to view :attr:`self` tensor as :attr:`shape`
    without copying it (e.g., via :meth:`contiguous`). When it is unclear whether a
    :meth:`view` can be performed, it is advisable to use :meth:`resh